version: '2'

services:
# myNode.js web service
  mynode:
    build: .
    image: mynode
    networks:
      - cyexc1a
    ports:
      - "8081:8081"

networks:
  cyexc1a:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.2.0/24
        gateway: 192.168.2.1
