version: '2'

services:
    # mySQL service
    db:
        image: mysql:5.7
        networks:
            cyexc3t:
                ipv4_address: 192.168.1.20
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress

    # wordpress service
    wordpress:
        depends_on:
            - db
        #image: wordpress:4.2.2
        build: ./WordPress
        image: mywp
        networks:
            cyexc3t:
                ipv4_address: 192.168.1.10
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:

networks:
  cyexc3t:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
