version: '2'

services:
# myNode.js web service
  webapp:
    build: ./webapp
    image: myweb
    networks:
      - cyexc2a
    ports:
      - "8081:8081"

networks:
  cyexc2a:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.2.0/24
        gateway: 192.168.2.1
